export const LINE_MOCK_ID_TOKEN = 'rogym-liff-mock-member-token'
export const LINE_MOCK_USER_ID = 'rogym-liff-mock-member'
export const LINE_MOCK_USER_EMAIL = 'liff.mock.member@gym.local'
export const LINE_MOCK_USER_NAME = 'LIFF Mock Member'
export const LINE_MOCK_WEBHOOK_SECRET = 'rogym-local-line-mock-webhook-secret'
