import type { Package } from '@/services/package.service'
import type { Exercise } from '@/services/workout.service'
import type { TimeSlot } from '@/components/ui'
import strengthImg from '@/assets/package-gallery/package-strength.jpg'
import cardioImg from '@/assets/package-gallery/package-cardio.jpg'
import trainingImg from '@/assets/package-gallery/package-training.jpg'
import recoveryImg from '@/assets/package-gallery/package-recovery.jpg'

export interface ShowcaseMember {
  id: string
  code: string
  name: string
  phone: string
  email: string
  plan: string
  status: 'active' | 'pending' | 'expired' | 'checked-in' | 'cancelled'
  joinDate: string
  expiryDate: string
  avatar?: string
  rfidCard: string
  sessionsLeft: number
  branch: string
}

export const SHOWCASE_MEMBERS: ShowcaseMember[] = [
  {
    id: 'mem_1',
    code: 'MEM-001',
    name: 'Nguyễn Văn An',
    phone: '0901 234 567',
    email: 'an.nguyen@example.com',
    plan: 'VIP 12 Tháng',
    status: 'active',
    joinDate: '15/01/2026',
    expiryDate: '15/01/2027',
    rfidCard: 'RFID-984210',
    sessionsLeft: 24,
    branch: 'Chi nhánh Quận 1 (Trụ sở)',
  },
  {
    id: 'mem_2',
    code: 'MEM-002',
    name: 'Trần Thị Bình',
    phone: '0912 345 678',
    email: 'binh.tran@example.com',
    plan: 'Standard 6 Tháng',
    status: 'active',
    joinDate: '20/02/2026',
    expiryDate: '20/08/2026',
    rfidCard: 'RFID-112039',
    sessionsLeft: 8,
    branch: 'Chi nhánh Quận 3',
  },
  {
    id: 'mem_3',
    code: 'MEM-003',
    name: 'Lê Hoàng Cường',
    phone: '0987 654 321',
    email: 'cuong.le@example.com',
    plan: 'Standard 1 Tháng',
    status: 'expired',
    joinDate: '10/11/2025',
    expiryDate: '10/12/2025',
    rfidCard: 'RFID-449102',
    sessionsLeft: 0,
    branch: 'Chi nhánh Quận 1',
  },
  {
    id: 'mem_4',
    code: 'MEM-004',
    name: 'Phạm Minh Đức',
    phone: '0978 112 233',
    email: 'duc.pham@example.com',
    plan: 'VIP 12 Tháng',
    status: 'pending',
    joinDate: '01/08/2026',
    expiryDate: '01/08/2027',
    rfidCard: 'RFID-381900',
    sessionsLeft: 30,
    branch: 'Chi nhánh Quận 7',
  },
  {
    id: 'mem_5',
    code: 'MEM-005',
    name: 'Hoàng Thuỳ Linh',
    phone: '0933 445 566',
    email: 'linh.hoang@example.com',
    plan: 'Standard 3 Tháng',
    status: 'active',
    joinDate: '14/05/2026',
    expiryDate: '14/08/2026',
    rfidCard: 'RFID-771829',
    sessionsLeft: 12,
    branch: 'Chi nhánh Quận 1',
  },
  {
    id: 'mem_6',
    code: 'MEM-006',
    name: 'Đặng Quốc Huy',
    phone: '0908 776 655',
    email: 'huy.dang@example.com',
    plan: 'VIP 6 Tháng',
    status: 'checked-in',
    joinDate: '10/03/2026',
    expiryDate: '10/09/2026',
    rfidCard: 'RFID-662910',
    sessionsLeft: 16,
    branch: 'Chi nhánh Quận 3',
  },
  {
    id: 'mem_7',
    code: 'MEM-007',
    name: 'Vũ Thị Ngọc Hà',
    phone: '0922 889 900',
    email: 'ha.vu@example.com',
    plan: 'Silver 1 Tháng',
    status: 'cancelled',
    joinDate: '05/01/2026',
    expiryDate: '05/02/2026',
    rfidCard: 'RFID-552811',
    sessionsLeft: 0,
    branch: 'Chi nhánh Quận 7',
  },
  {
    id: 'mem_8',
    code: 'MEM-008',
    name: 'Ngô Kiến Huy',
    phone: '0919 663 322',
    email: 'huy.ngo@example.com',
    plan: 'VIP 12 Tháng',
    status: 'active',
    joinDate: '02/06/2026',
    expiryDate: '02/06/2027',
    rfidCard: 'RFID-990182',
    sessionsLeft: 20,
    branch: 'Chi nhánh Quận 1',
  },
]

export const SHOWCASE_PACKAGES: Package[] = [
  {
    packageId: 'pkg_vip12',
    packageCode: 'VIP-12M',
    name: 'Gói Hội Viên VIP Toàn Diện (12 Tháng)',
    durationDays: 365,
    price: '12000000',
    benefits: 'Tập không giới hạn 24/7 tất cả chi nhánh\nTặng kèm 24 buổi huấn luyện viên cá nhân (PT 1:1)\nMiễn phí phòng xông hơi, bể sục Jacuzzi và tủ đồ VIP\nĐược dẫn theo 1 người bạn mỗi tháng\nMiễn phí đo chỉ số thể thân InBody định kỳ hàng tháng',
    includesPt: true,
    status: 'active',
    stats: {
      activeSubscriptions: 142,
      pendingSubscriptions: 12,
      totalSubscriptions: 356,
    },
    createdAt: '2025-01-01T00:00:00Z',
    deletedAt: null,
  },
  {
    packageId: 'pkg_std6',
    packageCode: 'STD-6M',
    name: 'Gói Tiêu Chuẩn Nâng Cao (6 Tháng)',
    durationDays: 180,
    price: '4800000',
    benefits: 'Tập không giới hạn trong khung giờ 06:00 - 22:00\nSử dụng toàn bộ khu tạ tự do, cardio và máy tập chuyên dụng\nTặng 03 buổi hướng dẫn nhập môn cùng Huấn luyện viên\nMiễn phí giữ xe và nước uống ion khoáng',
    includesPt: false,
    status: 'active',
    stats: {
      activeSubscriptions: 89,
      pendingSubscriptions: 6,
      totalSubscriptions: 210,
    },
    createdAt: '2025-01-15T00:00:00Z',
    deletedAt: null,
  },
  {
    packageId: 'pkg_std3',
    packageCode: 'STD-3M',
    name: 'Gói Tiêu Chuẩn Linh Hoạt (3 Tháng)',
    durationDays: 90,
    price: '2700000',
    benefits: 'Tập tự do tại chi nhánh đăng ký\nTrọn gói lớp Yoga, Zumba và Body Combat bản quyền\nMiễn phí 01 lần phân tích chỉ số cơ thể InBody 770',
    includesPt: false,
    status: 'active',
    stats: {
      activeSubscriptions: 64,
      pendingSubscriptions: 4,
      totalSubscriptions: 180,
    },
    createdAt: '2025-02-01T00:00:00Z',
    deletedAt: null,
  },
  {
    packageId: 'pkg_pt30',
    packageCode: 'PT-30S',
    name: 'Gói Huấn Luyện Viên Cá Nhân VIP (30 Buổi)',
    durationDays: 120,
    price: '15000000',
    benefits: '30 buổi huấn luyện 1:1 độc quyền cùng Master Trainer\nThiết kế giáo án dinh dưỡng và lộ trình bài tập cá nhân hóa\nCam kết hiệu quả giảm mỡ / tăng cơ theo hợp đồng\nBảo lưu linh hoạt tối đa 45 ngày khi đi công tác',
    includesPt: true,
    status: 'active',
    stats: {
      activeSubscriptions: 35,
      pendingSubscriptions: 2,
      totalSubscriptions: 95,
    },
    createdAt: '2025-03-01T00:00:00Z',
    deletedAt: null,
  },
]

export const SHOWCASE_TIME_SLOTS: TimeSlot[] = [
  {
    startTime: '2026-08-23T06:00:00.000Z',
    endTime: '2026-08-23T07:00:00.000Z',
    available: false,
    reason: 'PAST_TIME',
  },
  {
    startTime: '2026-08-23T07:30:00.000Z',
    endTime: '2026-08-23T08:30:00.000Z',
    available: false,
    reason: 'BUSY',
  },
  {
    startTime: '2026-08-23T09:00:00.000Z',
    endTime: '2026-08-23T10:00:00.000Z',
    available: true,
  },
  {
    startTime: '2026-08-23T10:30:00.000Z',
    endTime: '2026-08-23T11:30:00.000Z',
    available: true,
  },
  {
    startTime: '2026-08-23T14:00:00.000Z',
    endTime: '2026-08-23T15:00:00.000Z',
    available: false,
    reason: 'ROOM_FULL',
  },
  {
    startTime: '2026-08-23T15:30:00.000Z',
    endTime: '2026-08-23T16:30:00.000Z',
    available: true,
  },
  {
    startTime: '2026-08-23T17:00:00.000Z',
    endTime: '2026-08-23T18:00:00.000Z',
    available: false,
    reason: 'BUSY',
  },
  {
    startTime: '2026-08-23T18:30:00.000Z',
    endTime: '2026-08-23T19:30:00.000Z',
    available: true,
  },
]

export const SHOWCASE_EXERCISES: Exercise[] = [
  {
    exerciseId: 'ex_1',
    name: 'Barbell Bench Press (Đẩy ngực ngang với thanh đòn)',
    bodyPartId: 1,
    targetMuscleId: 1,
    equipmentId: 1,
    description: 'Bài tập phức hợp kinh điển xây dựng cơ ngực dày và tăng cường sức mạnh thân trên.',
    instructions: [
      'Nằm ngửa trên ghế phẳng, hai chân đặt chắc chắn trên sàn.',
      'Nắm thanh đòn rộng hơn vai một chút, khóa cổ tay và hạ đòn chậm rãi về giữa ngực.',
      'Thở ra và đẩy mạnh thanh đòn về vị trí ban đầu mà không khóa khớp khuỷu tay.',
    ],
    gifUrl: 'https://images.unsplash.com/photo-1571019614242-c5c5dee9f50b?w=600&auto=format&fit=crop&q=80',
    imageUrl: strengthImg,
    createdByStaffId: null,
    createdAt: '2025-01-01',
    deletedAt: null,
    bodyPart: { bodyPartId: 1, name: 'Ngực (Chest)' },
    targetMuscle: { muscleId: 1, name: 'Pectoralis Major' },
    equipment: { equipmentId: 1, name: 'Barbell / Ghế Bench' },
  },
  {
    exerciseId: 'ex_2',
    name: 'Barbell Back Squat (Gánh đùi sau)',
    bodyPartId: 2,
    targetMuscleId: 2,
    equipmentId: 1,
    description: 'Vua của các bài tập thân dưới, kích hoạt toàn bộ đùi trước, đùi sau và cơ mông.',
    instructions: [
      'Đặt thanh đòn trên cơ cầu vai (traps), mở chân rộng bằng vai.',
      'Hít sâu, siết chặt cơ bụng và hạ thấp hông như đang ngồi xuống ghế cho đến khi đùi song song với sàn.',
      'Dồn lực qua gót chân, đạp mạnh đứng dậy và thở ra.',
    ],
    gifUrl: 'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=600&auto=format&fit=crop&q=80',
    imageUrl: trainingImg,
    createdByStaffId: null,
    createdAt: '2025-01-01',
    deletedAt: null,
    bodyPart: { bodyPartId: 2, name: 'Chân & Đùi (Legs)' },
    targetMuscle: { muscleId: 2, name: 'Quadriceps / Glutes' },
    equipment: { equipmentId: 1, name: 'Squat Rack / Barbell' },
  },
  {
    exerciseId: 'ex_3',
    name: 'Lat Pulldown (Kéo xô máy cáp)',
    bodyPartId: 3,
    targetMuscleId: 3,
    equipmentId: 2,
    description: 'Phát triển độ rộng lưng chữ V, an toàn và dễ điều chỉnh khối lượng tạ.',
    instructions: [
      'Ngồi vào máy, cố định đùi dưới đệm giữ chân.',
      'Nắm thanh kéo rộng hơn vai, ưỡn ngực nhẹ.',
      'Kéo thanh đòn xuống sát xương quai xanh, ép chặt hai bả vai vào nhau trong 1 giây trước khi thả về.',
    ],
    gifUrl: 'https://images.unsplash.com/photo-1581009146145-b5ef050c2e1e?w=600&auto=format&fit=crop&q=80',
    imageUrl: cardioImg,
    createdByStaffId: null,
    createdAt: '2025-01-01',
    deletedAt: null,
    bodyPart: { bodyPartId: 3, name: 'Lưng & Xô (Back)' },
    targetMuscle: { muscleId: 3, name: 'Latissimus Dorsi' },
    equipment: { equipmentId: 2, name: 'Cable Machine' },
  },
  {
    exerciseId: 'ex_4',
    name: 'Dumbbell Shoulder Overhead Press (Đẩy vai tạ đôi)',
    bodyPartId: 4,
    targetMuscleId: 4,
    equipmentId: 3,
    description: 'Xây dựng bờ vai vuông vức, cải thiện độ linh hoạt khớp vai và sức mạnh cốt lõi.',
    instructions: [
      'Ngồi trên ghế tựa 90 độ, cầm đôi tạ đơn ngang tầm tai.',
      'Đẩy tạ thẳng lên trên đầu theo hình vòng cung nhẹ, không chạm tạ vào nhau ở đỉnh.',
      'Hạ tạ có kiểm soát về vị trí tai.',
    ],
    gifUrl: 'https://images.unsplash.com/photo-1583454110551-21f2fa2afe61?w=600&auto=format&fit=crop&q=80',
    imageUrl: recoveryImg,
    createdByStaffId: null,
    createdAt: '2025-01-01',
    deletedAt: null,
    bodyPart: { bodyPartId: 4, name: 'Vai (Shoulders)' },
    targetMuscle: { muscleId: 4, name: 'Deltoids' },
    equipment: { equipmentId: 3, name: 'Dumbbells' },
  },
]

export const SHOWCASE_WEIGHT_DATA = [
  { date: 'Thg 1', weight: 78.5 },
  { date: 'Thg 2', weight: 77.2 },
  { date: 'Thg 3', weight: 75.8 },
  { date: 'Thg 4', weight: 74.4 },
  { date: 'Thg 5', weight: 73.1 },
  { date: 'Thg 6', weight: 72.0 },
]

export const SHOWCASE_STUDENT_PROGRESS = [
  { date: 'Tuần 1', weight: 82.0, bmi: 26.5 },
  { date: 'Tuần 2', weight: 81.2, bmi: 26.2 },
  { date: 'Tuần 3', weight: 80.5, bmi: 26.0 },
  { date: 'Tuần 4', weight: 79.4, bmi: 25.6 },
  { date: 'Tuần 5', weight: 78.8, bmi: 25.4 },
  { date: 'Tuần 6', weight: 77.9, bmi: 25.1 },
]

export const SHOWCASE_NOTIFICATION_ITEMS = [
  {
    id: 'notif_1',
    title: 'Lịch tập PT sắp diễn ra',
    message: 'Buổi tập cá nhân cùng HLV Alex Mercer sẽ bắt đầu sau 45 phút tại Studio B.',
    time: '10 phút trước',
    unread: true,
    tone: 'info' as const,
  },
  {
    id: 'notif_2',
    title: 'Gia hạn gói tập thành công',
    message: 'Hóa đơn #INV-2026-8921 trị giá 12.000.000đ đã được thanh toán qua VNPay.',
    time: '2 giờ trước',
    unread: true,
    tone: 'success' as const,
  },
  {
    id: 'notif_3',
    title: 'Cảnh báo sắp hết hạn gói tập',
    message: 'Gói tập Tiêu chuẩn 3 Tháng của bạn còn lại 5 ngày. Vui lòng gia hạn để tiếp tục luyện tập.',
    time: '1 ngày trước',
    unread: false,
    tone: 'warning' as const,
  },
  {
    id: 'notif_4',
    title: 'Bảo trì hệ thống xông hơi',
    message: 'Khu vực Sauna chi nhánh Quận 1 sẽ tạm dừng hoạt động từ 12:00 đến 16:00 ngày mai.',
    time: '2 ngày trước',
    unread: false,
    tone: 'info' as const,
  },
]

export interface ComponentIndexItem {
  id: string
  name: string
  category: 'buttons' | 'forms' | 'overlays' | 'display' | 'nav' | 'feedback' | 'domain-flows'
  tab: string
  description: string
  tags: string[]
  snippet?: string
}

export const COMPONENT_INDEX_CATALOG: ComponentIndexItem[] = [
  {
    id: 'button',
    name: 'Button',
    category: 'buttons',
    tab: 'buttons',
    description: 'Nút bấm đa biến thể chuẩn hóa: primary, secondary, danger, outline, text.',
    tags: ['button', 'action', 'click', 'variants', 'loading'],
    snippet: '<Button variant="primary" size="default">Bấm vào đây</Button>',
  },
  {
    id: 'submit-button',
    name: 'SubmitButton',
    category: 'buttons',
    tab: 'buttons',
    description: 'Nút gửi form tự động hiển thị hiệu ứng xoay khi loading.',
    tags: ['submit', 'form', 'loading', 'save'],
    snippet: '<SubmitButton loading={isLoading}>Lưu thông tin</SubmitButton>',
  },
  {
    id: 'back-button',
    name: 'BackButton',
    category: 'buttons',
    tab: 'buttons',
    description: 'Nút quay lại trang trước với icon và nhãn tùy biến.',
    tags: ['back', 'return', 'navigation', 'history'],
    snippet: '<BackButton label="Quay lại danh sách" />',
  },
  {
    id: 'input',
    name: 'Input',
    category: 'forms',
    tab: 'forms',
    description: 'Ô nhập liệu văn bản với left/right icon, trạng thái lỗi và disabled.',
    tags: ['input', 'text', 'form', 'password', 'search'],
    snippet: '<Input placeholder="Nhập tên..." leftIcon={<User size={16} />} />',
  },
  {
    id: 'form-field',
    name: 'FormField',
    category: 'forms',
    tab: 'forms',
    description: 'Bọc input tự động gắn nhãn label, gợi ý hint, và thông báo lỗi.',
    tags: ['form', 'field', 'label', 'error', 'hint'],
    snippet: '<FormField label="Họ tên" required error="Bắt buộc">\n  <Input />\n</FormField>',
  },
  {
    id: 'search-input',
    name: 'SearchInput & SearchToolbar',
    category: 'forms',
    tab: 'forms',
    description: 'Thanh tìm kiếm có debounce, clear button và thanh toolbar lọc dữ liệu.',
    tags: ['search', 'debounce', 'toolbar', 'filter'],
    snippet: '<SearchInput value={query} onChange={setQuery} placeholder="Tìm kiếm..." />',
  },
  {
    id: 'combobox',
    name: 'Combobox',
    category: 'forms',
    tab: 'forms',
    description: 'Hộp chọn có tìm kiếm lọc option mượt mà, hỗ trợ bàn phím.',
    tags: ['combobox', 'select', 'searchable', 'dropdown'],
    snippet: '<Combobox options={options} value={val} onValueChange={setVal} />',
  },
  {
    id: 'time-slot-picker',
    name: 'TimeSlotPicker',
    category: 'forms',
    tab: 'forms',
    description: 'Bộ chọn khung giờ tập PT hiển thị trực quan các slot trống và bận.',
    tags: ['timeslot', 'pt', 'booking', 'schedule'],
    snippet: '<TimeSlotPicker slots={slots} selectedSlot={slot} onSelectSlot={setSlot} />',
  },
  {
    id: 'file-upload',
    name: 'FileUpload',
    category: 'forms',
    tab: 'forms',
    description: 'Tải file và ảnh đại diện với chế độ avatar hoặc dropzone kéo thả.',
    tags: ['file', 'upload', 'avatar', 'dropzone'],
    snippet: '<FileUpload variant="avatar" />',
  },
  {
    id: 'tag-input',
    name: 'TagInput',
    category: 'forms',
    tab: 'forms',
    description: 'Nhập danh sách tags với phím Enter, xóa nhanh bằng X.',
    tags: ['tag', 'chips', 'keywords'],
    snippet: '<TagInput value={tags} onChange={setTags} />',
  },
  {
    id: 'modal',
    name: 'Modal',
    category: 'overlays',
    tab: 'overlays',
    description: 'Hộp thoại popup đa kích cỡ (sm, md, lg, xl, full) với focus trapping.',
    tags: ['modal', 'dialog', 'popup'],
    snippet: '<Modal open={isOpen} onClose={() => setOpen(false)} title="Tiêu đề">\n  Nội dung\n</Modal>',
  },
  {
    id: 'confirm-dialog',
    name: 'ConfirmDialog',
    category: 'overlays',
    tab: 'overlays',
    description: 'Hộp thoại xác nhận hành động nguy hiểm (danger/warning) kèm async loading.',
    tags: ['confirm', 'delete', 'alert', 'dialog'],
    snippet: '<ConfirmDialog open={isOpen} onClose={close} onConfirm={handleDelete} title="Xác nhận?" />',
  },
  {
    id: 'sheet',
    name: 'Sheet (Drawer)',
    category: 'overlays',
    tab: 'overlays',
    description: 'Ngăn kéo trượt từ 4 hướng (phải, dưới, trái, trên) tối ưu mobile.',
    tags: ['sheet', 'drawer', 'slideover', 'mobile'],
    snippet: '<Sheet open={isOpen} onOpenChange={setOpen}>\n  <SheetContent side="right">\n    Nội dung\n  </SheetContent>\n</Sheet>',
  },
  {
    id: 'dropdown-menu',
    name: 'DropdownMenu',
    category: 'overlays',
    tab: 'overlays',
    description: 'Menu tùy chọn ngữ cảnh nhiều cấp (submenu), checkbox và radio.',
    tags: ['dropdown', 'menu', 'context', 'actions'],
    snippet: '<DropdownMenu>\n  <DropdownMenuTrigger>Mở</DropdownMenuTrigger>\n  <DropdownMenuContent>...</DropdownMenuContent>\n</DropdownMenu>',
  },
  {
    id: 'responsive-table',
    name: 'ResponsiveTable & Pagination',
    category: 'display',
    tab: 'display',
    description: 'Bảng dữ liệu responsive tự co giãn trên mobile kèm phân trang.',
    tags: ['table', 'datatable', 'pagination', 'responsive'],
    snippet: '<ResponsiveTable columns={columns} data={data} keyExtractor={row => row.id} />',
  },
  {
    id: 'card',
    name: 'Card & CardMedia & CardRibbon',
    category: 'display',
    tab: 'display',
    description: 'Thẻ thông tin linh hoạt với hình ảnh nhiều tỉ lệ và ruy băng nhãn HOT.',
    tags: ['card', 'container', 'ribbon', 'media'],
    snippet: '<Card>\n  <CardHeader><CardTitle>Tiêu đề</CardTitle></CardHeader>\n</Card>',
  },
  {
    id: 'stat-card',
    name: 'StatCard',
    category: 'display',
    tab: 'display',
    description: 'Thẻ thống kê số liệu tổng quan với icon và chỉ số tăng trưởng.',
    tags: ['stat', 'metrics', 'kpi', 'dashboard'],
    snippet: '<StatCard label="Tổng hội viên" value="1,248" trend={{ value: "+12%", isPositive: true }} />',
  },
  {
    id: 'avatar',
    name: 'Avatar & AvatarGroup',
    category: 'display',
    tab: 'display',
    description: 'Ảnh đại diện người dùng kèm chỉ báo trạng thái online/offline và nhóm avatar.',
    tags: ['avatar', 'profile', 'group', 'user'],
    snippet: '<Avatar name="Nguyễn Văn An" status="online" size="md" />',
  },
  {
    id: 'page-ui',
    name: 'PageUI Ecosystem',
    category: 'nav',
    tab: 'nav',
    description: 'PageHeader chuẩn hóa, PageSkeleton tải trang và PageEmptyState.',
    tags: ['page', 'header', 'skeleton', 'empty'],
    snippet: '<PageHeader title="Tiêu đề trang" description="Mô tả" actions={<Button>Tạo mới</Button>} />',
  },
  {
    id: 'stepper',
    name: 'Stepper',
    category: 'nav',
    tab: 'nav',
    description: 'Thanh tiến trình nhiều bước wizard cho quy trình đăng ký dịch vụ.',
    tags: ['stepper', 'wizard', 'steps', 'flow'],
    snippet: '<Stepper activeStep={1} steps={[{ title: "Bước 1" }, { title: "Bước 2" }]} />',
  },
  {
    id: 'alert',
    name: 'Alert & Toast',
    category: 'feedback',
    tab: 'feedback',
    description: 'Thông báo trạng thái inline và thông báo popover Sonner toast.',
    tags: ['alert', 'toast', 'notification', 'feedback', 'sonner'],
    snippet: '<Alert tone="success" title="Thành công" description="Đã lưu thay đổi" />',
  },
  {
    id: 'flow-package-picker',
    name: 'Gym Flow: PackagePicker',
    category: 'domain-flows',
    tab: 'domain-flows',
    description: 'Flow thực tế chọn gói tập, xem danh sách đặc quyền và mở Lightbox thư viện ảnh.',
    tags: ['package', 'lightbox', 'gallery', 'pricing', 'gym'],
    snippet: '<PackagePicker packages={packages} selectedPackageId={id} onSelectPackage={setId} />',
  },
  {
    id: 'flow-exercise-library',
    name: 'Gym Flow: ExerciseCard & Workout',
    category: 'domain-flows',
    tab: 'domain-flows',
    description: 'Flow thư viện bài tập gym có GIF animation khi hover và lọc nhóm cơ.',
    tags: ['exercise', 'workout', 'gif', 'muscle', 'gym'],
    snippet: '<ExerciseCard exercise={exercise} onClick={() => openModal(exercise)} />',
  },
  {
    id: 'flow-charts',
    name: 'Gym Flow: Weight & Progress Charts',
    category: 'domain-flows',
    tab: 'domain-flows',
    description: 'Biểu đồ Recharts theo dõi cân nặng hội viên và chỉ số BMI học viên của PT.',
    tags: ['chart', 'recharts', 'weight', 'bmi', 'progress'],
    snippet: '<MemberWeightChart data={weightData} />',
  },
]
