@startuml
start

:会員がフィードバックを送信;

:管理スタッフが受け取る;

:重要度を分類;

if (設備についてか?) then (Yes)
  :技術担当へ回す;
  :修理する;
elseif (スタッフについてか?) then (Yes)
  :人事担当へ回す;
  :注意または評価する;
else (サービス)
  :サービス問題を処理;
endif

:処理結果をシステムに登録;

:会員へ結果を通知;

stop
@enduml