@startuml
start

:ジムオーナーが権限管理を開く;

if (ユーザーにグループを割り当てるか?) then (Yes)
  :対象ユーザーを選ぶ;
  :権限グループを選ぶ;
  :ユーザーにグループを割り当てる;

elseif (グループのユーザーを管理するか?) then (Yes)
  :権限グループを選ぶ;
  :メンバー一覧を表示;

  if (メンバーを追加するか?) then (Yes)
    :社員番号を検索;
    :グループに追加;
  else (削除)
    :メンバーを選ぶ;
    :グループから削除;
  endif

else (グループの機能を管理する)
  :設定したいグループを選ぶ;
  :機能一覧を表示;
  :権限を選択/解除;
endif

:変更を保存;

:システムが権限を更新;

stop
@enduml